@ stdcall ChooseColorA(ptr)
@ stdcall ChooseColorW(ptr)
@ stdcall ChooseFontA(ptr)
@ stdcall ChooseFontW(ptr)
@ stdcall CommDlgExtendedError()
;@ stdcall -private DllGetClassObject(ptr ptr ptr) ; Win 7
;@ stdcall -private DllRegisterServer() ; Win 7
;@ stdcall -private DllUnregisterServer() ; Win 7
@ stdcall FindTextA(ptr)
@ stdcall FindTextW(ptr)
@ stdcall GetFileTitleA(str ptr long)
@ stdcall GetFileTitleW(wstr ptr long)
@ stdcall GetOpenFileNameA(ptr)
@ stdcall GetOpenFileNameW(ptr)
@ stdcall GetSaveFileNameA(ptr)
@ stdcall GetSaveFileNameW(ptr)
@ stdcall -stub LoadAlterBitmap(long long long)
@ stdcall PageSetupDlgA(ptr)
@ stdcall PageSetupDlgW(ptr)
@ stdcall PrintDlgA(ptr)
@ stdcall PrintDlgExA(ptr)
@ stdcall PrintDlgExW(ptr)
@ stdcall PrintDlgW(ptr)
@ stdcall ReplaceTextA(ptr)
@ stdcall ReplaceTextW(ptr)
@ stdcall -stub WantArrows(long long ptr ptr)
@ stdcall -stub dwLBSubclass(long long ptr ptr)
@ stdcall -stub dwOKSubclass(long long ptr ptr)
@ stdcall -stub Ssync_ANSI_UNICODE_Struct_For_WOW(long long long)
100 stdcall -noname -stub FormatCharDlgProc(long long long long)
