@ stdcall ChooseColorA(ptr)
@ stdcall ChooseColorW(ptr)
@ stdcall ChooseFontA(ptr)
@ stdcall ChooseFontW(ptr)
@ stdcall CommDlgExtendedError()
@ stdcall DllGetClassObject(ptr ptr ptr)
; @ stdcall -private -stub DllRegisterServer()
; @ stdcall -private -stub DllUnregisterServer()
@ stdcall FindTextA(ptr)
@ stdcall FindTextW(ptr)
@ stdcall GetFileTitleA(str ptr long)
@ stdcall GetFileTitleW(wstr ptr long)
@ stdcall GetOpenFileNameA(ptr)
@ stdcall GetOpenFileNameW(ptr)
@ stdcall GetSaveFileNameA(ptr)
@ stdcall GetSaveFileNameW(ptr)
@ stdcall LoadAlterBitmap(long long long)
@ stdcall PageSetupDlgA(ptr)
@ stdcall PageSetupDlgW(ptr)
@ stdcall PrintDlgA(ptr)
@ stdcall PrintDlgExA(ptr)
@ stdcall PrintDlgExW(ptr)
@ stdcall PrintDlgW(ptr)
@ stdcall ReplaceTextA(ptr)
@ stdcall ReplaceTextW(ptr)
@ stdcall WantArrows(long long ptr ptr)
@ stdcall dwLBSubclass(long long ptr ptr)
@ stdcall dwOKSubclass(long long ptr ptr)
@ stdcall Ssync_ANSI_UNICODE_Struct_For_WOW(long long long)
100 stdcall -noname FormatCharDlgProc(long long long long)
