132 stdcall CreateEnvironmentBlock(ptr ptr long)
133 stdcall DeleteProfileA(str str str)
134 stdcall DeleteProfileW(wstr wstr wstr)
176 stdcall DestroyEnvironmentBlock(ptr)
@ stdcall DllCanUnloadNow()                                    #stdcall DllCanUnloadNow()
@ stdcall DllGetClassObject(ptr ptr ptr)                       #stdcall DllGetClassObject(ptr ptr ptr)
@ stdcall DllInstall(long wstr)                                #stdcall DllInstall(long wstr)
@ stdcall DllRegisterServer()                                  #stdcall DllRegisterServer()
@ stdcall DllUnregisterServer()                                #stdcall DllUnregisterServer()
182 stdcall EnterCriticalPolicySection(long)
183 stdcall ExpandEnvironmentStringsForUserA(ptr str str long)
184 stdcall ExpandEnvironmentStringsForUserW(ptr wstr wstr long)
185 stdcall ForceSyncFgPolicy(wstr)                                          #stdcall ForceSyncFgPolicy(4)
186 stdcall FreeGPOListA(ptr)                                                  #stdcall FreeGPOListA(ptr)
187 stdcall FreeGPOListW(ptr)                                                 #stdcall FreeGPOListW(ptr)
188 stdcall GenerateRsopPolicy(long wstr wstr ptr wstr wstr ptr wstr ptr ptr ptr)                                           #stdcall GenerateRsopPolicy(48)
189 stdcall GetAllUsersProfileDirectoryA(str ptr)
190 stdcall GetAllUsersProfileDirectoryW(wstr ptr)
191 stdcall GetAppliedGPOListA(long str ptr ptr ptr)                                         #stdcall GetAppliedGPOListA(long str ptr ptr ptr)
192 stdcall GetAppliedGPOListW(long wstr ptr ptr ptr)                                          #stdcall GetAppliedGPOListW(long wstr ptr ptr ptr)
193 stdcall GetDefaultUserProfileDirectoryA(str ptr)
194 stdcall GetDefaultUserProfileDirectoryW(wstr ptr)
195 stdcall GetGPOListA(ptr str str str long ptr)                                                  #stdcall GetGPOListA(ptr str str str long ptr)
196 stdcall GetGPOListW(ptr wstr wstr wstr long ptr)                                                #stdcall GetGPOListW(ptr wstr wstr wstr long ptr)
197 stdcall -stub GetNextFgPolicyRefreshInfo(wstr ptr)                                   #stdcall GetNextFgPolicyRefreshInfo(8)
198 stdcall -stub GetPreviousFgPolicyRefreshInfo(wstr ptr)                              #stdcall GetPreviousFgPolicyRefreshInfo(8)
199 stdcall GetProfileType(ptr)
202 stdcall GetProfilesDirectoryA(str ptr)
203 stdcall GetProfilesDirectoryW(wstr ptr)
204 stdcall GetUserProfileDirectoryA(ptr str ptr)
205 stdcall GetUserProfileDirectoryW(ptr wstr ptr)
206 stdcall LeaveCriticalPolicySection(ptr)
207 stdcall LoadUserProfileA(ptr ptr)
208 stdcall LoadUserProfileW(ptr ptr)
209 stdcall ProcessGroupPolicyCompleted(ptr ptr long)                                  #stdcall ProcessGroupPolicyCompleted(ptr ptr long)
210 stdcall ProcessGroupPolicyCompletedEx(ptr ptr long ptr)                                #stdcall ProcessGroupPolicyCompletedEx(ptr ptr long ptr)
211 stdcall RefreshPolicy(long)
212 stdcall RefreshPolicyEx(long long)
213 stdcall RegisterGPNotification(ptr long)
214 stdcall -stub RsopAccessCheckByType(ptr ptr ptr long ptr long ptr ptr ptr ptr ptr)                                        #stdcall RsopAccessCheckByType(ptr ptr ptr long ptr long ptr ptr ptr ptr ptr)
215 stdcall -stub RsopFileAccessCheck(wstr ptr long ptr ptr)                                          #stdcall RsopFileAccessCheck(wstr ptr long ptr ptr)
216 stdcall RsopLoggingEnabled()                                           #stdcall RsopLoggingEnabled()
217 stdcall -stub RsopResetPolicySettingStatus(long ptr ptr)                                 #stdcall RsopResetPolicySettingStatus(long ptr ptr)
218 stdcall -stub RsopSetPolicySettingStatus(long ptr ptr long ptr)                                   #stdcall RsopSetPolicySettingStatus(long ptr ptr long ptr)
219 stdcall UnloadUserProfile(ptr ptr)
220 stdcall UnregisterGPNotification(ptr)
221 stdcall WaitForMachinePolicyForegroundProcessing()
222 stdcall WaitForUserPolicyForegroundProcessing()
100 stdcall -noname InitializeProfiles()
101 stdcall -noname CreateGroupA(str long)
102 stdcall -noname CreateGroupW(wstr long)
103 stdcall -noname DeleteGroupA(str long)
104 stdcall -noname DeleteGroupW(wstr long)
105 stdcall -noname AddItemA(str long str str str long str long long)
106 stdcall -noname AddItemW(wstr long wstr wstr wstr long wstr long long)
107 stdcall -noname DeleteItemA(str long str long)
108 stdcall -noname DeleteItemW(wstr long wstr long)
109 stdcall -noname CreateUserProfileA(ptr str)
110 stdcall -noname CreateUserProfileW(ptr wstr)
111 stdcall -noname CopyProfileDirectoryA(str str long)
112 stdcall -noname CopyProfileDirectoryW(wstr wstr long)
113 stdcall -noname AddDesktopItemA(long str str str long str long long)
114 stdcall -noname AddDesktopItemW(long wstr wstr wstr long wstr long long)
115 stdcall -noname DeleteDesktopItemA(long str)
116 stdcall -noname DeleteDesktopItemW(long wstr)
117 stdcall -stub -noname ApplyGroupPolicy(long ptr ptr ptr ptr)                                     #stdcall -noname ApplyGroupPolicy(20)
118 stdcall -stub -noname ShutdownGPOProcessing(long)                               #stdcall -noname ShutdownGPOProcessing(4)
119 stdcall -stub -noname CreateLinkFileA(long str str str str long str long long str)                                     #stdcall -noname CreateLinkFileA(40)
120 stdcall -stub -noname CreateLinkFileW(long wstr wstr wstr wstr long wstr long long wstr)                                       #stdcall -noname CreateLinkFileW(40)
121 stdcall -stub -noname DeleteLinkFileA(long str str long)                                      #stdcall -noname DeleteLinkFileA(16)
122 stdcall -stub -noname DeleteLinkFileW(long wstr wstr long)                                      #stdcall -noname DeleteLinkFileW(16)
123 stdcall -stub -noname CopyProfileDirectoryExA(str str long ptr str)                              #stdcall -noname CopyProfileDirectoryExA(20)
124 stdcall -stub -noname CopyProfileDirectoryExW(wstr wstr long ptr wstr)                              #stdcall -noname CopyProfileDirectoryExW(20)
125 stdcall -stub -noname GetSystemTempDirectoryA(str ptr)                              #stdcall -noname GetSystemTempDirectoryA(8)
126 stdcall -stub -noname GetSystemTempDirectoryW(wstr ptr)                              #stdcall -noname GetSystemTempDirectoryW(8)
127 stdcall -stub -noname MigrateNT4ToNT5()                                      #stdcall -noname MigrateNT4ToNT5()
128 stdcall -stub -noname ResetUserSpecialFolderPaths()                          #stdcall -noname ResetUserSpecialFolderPaths()
129 stdcall -stub -noname ApplySystemPolicyA(long ptr ptr str str str)                                   #stdcall -noname ApplySystemPolicyA(24)
130 stdcall -stub -noname ApplySystemPolicyW(long ptr ptr wstr wstr wstr)                                    #stdcall -noname ApplySystemPolicyW(24)
131 stdcall -stub -noname DetermineProfilesLocation(long)                            #stdcall -noname DetermineProfilesLocation(4)
135 stdcall -stub -noname PingComputer(long ptr)                                         #stdcall -noname PingComputer(8)
136 stdcall -stub -noname CreateGroupExA(str long str long)                                       #stdcall -noname CreateGroupExA(16)
137 stdcall -stub -noname CreateGroupExW(wstr long wstr long)                                       #stdcall -noname CreateGroupExW(16)
138 stdcall -stub -noname CreateLinkFileExA(long str str str str long str long long str str long)                                    #stdcall -noname CreateLinkFileExA(48)
139 stdcall -stub -noname CreateLinkFileExW(long wstr wstr wstr wstr long wstr long long wstr wstr long)                                    #stdcall -noname CreateLinkFileExW(48)
140 stdcall -noname InitializeUserProfile()                                #stdcall -noname InitializeUserProfile()
141 stdcall -stub -noname RsopSidsFromToken(ptr ptr)
142 stdcall -noname GetUserSid(ptr)                                           #stdcall -noname GetUserSid(4)
143 stdcall -noname SecureUserProfiles()                                   #stdcall -noname SecureUserProfiles()
144 stdcall -noname EnterUserProfileLock(long) ;pode ser string                                #stdcall -noname EnterUserProfileLock(4)
145 stdcall -noname LeaveUserProfileLock(long) ;pode ser string                                    #stdcall -noname LeaveUserProfileLock(4)
146 stdcall -noname CheckAccessForPolicyGeneration(ptr wstr wstr long long)                       #stdcall -noname CheckAccessForPolicyGeneration(20)
147 stdcall -noname GetGroupPolicyNetworkName(ptr ptr)                           	   #stdcall -noname GetGroupPolicyNetworkName(8)
148 stdcall -noname GetUserAppDataPathA(ptr long str)                                  #stdcall -noname GetUserAppDataPathA(12)
149 stdcall -noname GetUserAppDataPathW(ptr long wstr)                                 #stdcall -noname GetUserAppDataPathW(12)
150 stdcall -noname SignalUserPolicyForegroundProcessingDone()       		 	       #stdcall -noname SignalUserPolicyForegroundProcessingDone()
151 stdcall -noname SignalMachinePolicyForegroundProcessingDone()    		     	   #stdcall -noname SignalMachinePolicyForegroundProcessingDone()
152 stdcall -noname IsSyncForegroundPolicyRefresh(long ptr)                      	   #stdcall -noname IsSyncForegroundPolicyRefresh(8)
153 stdcall -noname CreateUserProfileExA(ptr str str str long long)
154 stdcall -noname CreateUserProfileExW(ptr wstr wstr wstr long long)
155 stdcall -noname CopySystemProfile(ptr)                     			                #stdcall -noname CopySystemProfile(4)
156 stdcall -noname GetUserProfileDirFromSidA(ptr str ptr)        	                    #stdcall -noname GetUserProfileDirFromSidA(12)
157 stdcall -noname GetUserProfileDirFromSidW(ptr wstr ptr)                             #stdcall -noname GetUserProfileDirFromSidW(12)
158 stdcall -stub -noname SetNextFgPolicyRefreshInfo(wstr ptr)                           #stdcall -noname SetNextFgPolicyRefreshInfo(12)
159 stdcall -stub -noname TranslateNameXForest(str str ptr ptr str)                                 #stdcall -noname TranslateNameXForest(20)
160 stdcall -stub -noname AllocGpContainer(long long long long long str str str str ptr long long wstr wstr long)                                     #stdcall -noname AllocGpContainer(60)
161 stdcall -stub -noname AddGPO(ptr long long long long long long str str str str str ptr long ptr str long long long long long)                                               #stdcall -noname AddGPO(84)
162 stdcall -stub -noname GetWbemServices(ptr wstr long ptr ptr)                                      #stdcall -noname GetWbemServices(20)
163 stdcall -stub -noname FilterGPOs(ptr ptr)                                           #stdcall -noname FilterGPOs(8)
164 stdcall -stub -noname ProcessMachAndUserGpoList(ptr ptr long wstr wstr wstr ptr ptr wstr wstr ptr ptr)                            #stdcall -noname ProcessMachAndUserGpoList(48)
165 stdcall -stub -noname GPOExceptionFilter(ptr)                                   #stdcall -noname GPOExceptionFilter(4)
166 stdcall -stub -noname LogExtSessionStatus(ptr ptr long long)                                  #stdcall -noname LogExtSessionStatus(16)
167 stdcall -stub -noname UpdateExtSessionStatus(ptr str long long)                               #stdcall -noname UpdateExtSessionStatus(16)
168 stdcall -stub -noname UnloadGPExtensions(ptr)                                   #stdcall -noname UnloadGPExtensions(4)
169 stdcall -stub -noname FreeGpoInfo(ptr)                                          #stdcall -noname FreeGpoInfo(4)
170 stdcall -stub -noname LogSessionData(ptr ptr)                                       #stdcall -noname LogSessionData(8)
171 stdcall -stub -noname LogGpoData(ptr)                                           #stdcall -noname LogGpoData(4)
172 stdcall -stub -noname ReadGPExtensions(ptr)                                     #stdcall -noname ReadGPExtensions(4)
173 stdcall -stub -noname CheckForSkippedExtensions(ptr long)                            #stdcall -noname CheckForSkippedExtensions(8)
174 stdcall -stub -noname SetupGPOFilter(ptr)                                       #stdcall -noname SetupGPOFilter(4)
175 stdcall -stub CheckXForestLogon(ptr)                                    #stdcall -noname CheckXForestLogon(4)
200 stdcall -stub -noname CreateURLFile(wstr long ptr wstr long long long ptr ptr)                                        #stdcall -noname CreateURLFile(36)
201 stdcall -stub -noname DeleteURLFile(ptr wstr wstr ptr)                                        #stdcall -noname DeleteURLFile(16)
